version: 0.2
phases:
  pre_build:
    commands:
  build:
    commands:
      - mvn clean install -P code.coverage
      - mv target/test-lambda-*.jar target/main.jar
  post_build:
    commands:
      - curl -s https://codecov.tools.a.intuit.com/bash | bash -s -- -K

artifacts:
  discard-paths: yes
  files:
    - target/main.jar
    - template.yaml

cache:
  paths:
    - '/root/.m2/**/*'
