site_name: GraphQL Orchestrator Documentation
site_description: GraphQL Orchestrator Documentation
docs_dir: docs
theme:
  name: material
#  logo:
#    icon: home
  font:
    text: Work Sans
    code: Menlo
  favicon: img/graphql.ico
extra_css: ["css/css-override.css"]
repo_url: "https://github.com/intuit/graphql-orchestrator-java"
repo_name: 'graphql-orchestrator-java'
copyright: 'Copyright &copy; 2021 Intuit'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Key Concepts:
      - High Level Algorithm: key-concepts/algorithm.md
      - Recursive Schema Stitching: key-concepts/merging-types.md
      - GraphQL Query Execution: key-concepts/graphql-query-execution.md
      - Handling Interfaces and Unions: key-concepts/interface-union-types.md
      - Remote Type Extensions: key-concepts/field-links.md
      - Conflict Resolution: key-concepts/conflict-resolution.md
  - Specifications:
      - Custom Directives: specifications/custom-directives.md

